# Generated by Django 3.2.7 on 2021-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dish_in_order',
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(related_name='orders', to='webapp.Dish', verbose_name='Dish in order'),
        ),
    ]
