# Generated by Django 3.2.7 on 2021-09-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210925_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
    ]
