# Generated by Django 3.2.7 on 2021-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_orderdish_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdish',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
