# Generated by Django 3.2.7 on 2021-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_orderdish_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdish',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
