# Generated by Django 3.2.7 on 2021-09-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_orderdish_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdish',
            old_name='dish_id',
            new_name='dish_in_order',
        ),
        migrations.RenameField(
            model_name='orderdish',
            old_name='order_id',
            new_name='order',
        ),
    ]
